services:
  - type: web
    name: owlTester
    env: python
    repo: https://github.com/dkoepsell/FOL-BFO-OWL-tester
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      wget -O corretto.tar.gz https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
      tar -xzf corretto.tar.gz
      mv amazon-corretto-17* jdk-17
      export JAVA_HOME=$(pwd)/jdk-17
      export PATH=$JAVA_HOME/bin:$PATH
      echo "export JAVA_HOME=$(pwd)/jdk-17" >> $HOME/.bashrc
      echo "export PATH=$JAVA_HOME/bin:$PATH" >> $HOME/.bashrc
    startCommand: gunicorn -b 0.0.0.0:8080 app:app
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_HOME
        value: /opt/render/project/src/jdk-17
