services:
  - type: web
    name: owlTester
    env: python
    repo: https://github.com/dkoepsell/FOL-BFO-OWL-tester
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      curl -LO https://download.bell-sw.com/java/17.0.8.1+1/bellsoft-jdk17.0.8.1+1-linux-amd64.tar.gz
      tar -xzf bellsoft-jdk17.0.8.1+1-linux-amd64.tar.gz
      export JAVA_HOME=$(pwd)/jdk-17.0.8.1
      export PATH=$JAVA_HOME/bin:$PATH
    startCommand: gunicorn -b 0.0.0.0:8080 app:app
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_HOME
        value: /opt/render/project/src/jdk-17.0.8.1
