services:
  - type: web
    name: owlTester
    env: python
    repo: https://github.com/dkoepsell/FOL-BFO-OWL-tester
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      sdk install java 17.0.8-tem
      export JAVA_HOME="$HOME/.sdkman/candidates/java/current"
      export PATH="$JAVA_HOME/bin:$PATH"
    startCommand: gunicorn -b 0.0.0.0:8080 app:app
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_HOME
        value: $HOME/.sdkman/candidates/java/current
