services:
  - type: web
    name: owlTester
    env: python
    repo: https://github.com/dkoepsell/FOL-BFO-OWL-tester
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.8.1%2B1/OpenJDK17U-jdk_x64_linux_hotspot_17.0.8.1_1.tar.gz
      tar -xvzf OpenJDK17U-jdk_x64_linux_hotspot_17.0.8.1_1.tar.gz
      export JAVA_HOME=$(pwd)/jdk-17.0.8.1
      export PATH=$JAVA_HOME/bin:$PATH
    startCommand: gunicorn -b 0.0.0.0:8080 app:app
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_HOME
        value: /opt/render/project/src/jdk-17.0.8.1
